{% set version = "1.0" %}

package:
  name: autoasv
  version: 1.0

source:
  git_url: https://github.com/anttonalberdi/autoasv.git

requirements:
  build:
    - python
    - setuptools
    - snakemake-minimal 6.3.0*
    - biopython 1.78*
    - ruamel.yaml 0.16.12*
    - cutadapt 2.10*
    - bbmap 38.87*
    - r 4.0.0*
    - r-devtools 2.4.1*
    - bioconductor-dada2 1.18.0*
    - r-dplyr 1.0.6*
    - r-stringr 1.4.0*
    - r-optparse 1.6.6*
    - r-gtools 3.8.2*
    - r-ape 5.5*
    - perl-statistics-descriptive 3.0702*
    - gawk 5.1.0*
    - vsearch 2.15.2*
    - clustalo 1.2.4*
    - iqtree 2.0.3*

  run:
    - python
    - snakemake-minimal 6.3.0*
    - biopython 1.78*
    - ruamel.yaml 0.16.12*
    - cutadapt 2.10*
    - bbmap 38.87*
    - r 4.0.0*
    - r-devtools 2.4.1*
    - bioconductor-dada2 1.18.0*
    - r-dplyr 1.0.6*
    - r-stringr 1.4.0*
    - r-optparse 1.6.6*
    - r-gtools 3.8.2*
    - r-ape 5.5*
    - perl-statistics-descriptive 3.0702*
    - gawk 5.1.0*
    - vsearch 2.15.2*
    - clustalo 1.2.4*
    - iqtree 2.0.3*
