{% set version = "1.0" %}

package:
  name: autoasv
  version: 1.0

source:
  git_url: https://github.com/anttonalberdi/autoasv.git

requirements:
  build:
    - python
    - setuptools
    - snakemake-minimal 6.3.0*
    - biopython 1.78*
    - ruamel.yaml 0.16.12*
  run:
    - python
    - snakemake-minimal 6.3.0*
    - biopython 1.78*
    - ruamel.yaml 0.16.12*
